### ISSUE TITLE
Parser expects there to be a components/messages property in the main schema

### ISSUE THREAD

**Issue by karlwbrown** [WaleedAshraf/asyncapi-validator#11]
The message validator loads the schema messages as follows:
    this._messages = this._schema.components.messages

However, the schema messages could be in another file, such as through a reference as follows:
```
channels:
  test:
    publish:
      message:
        oneOf:
          - $ref: './ref1.yml#components/messages/msg1'
          - $ref: './ref2.yml#components/messages/msg2'
```

Additionally, the logic assumes that all messages are in components/messages, which isn't always the case - the spec will allow messages to be placed directly under channels.

Could the parser be updated to actually parse the schema, and then walk down the tree accordingly?
