### ISSUE TITLE
custom validation: how to call validate()

### ISSUE THREAD

**Issue by nospam2000** [WaleedAshraf/asyncapi-validator#27]
I'd like to have a custom validation for my asyncapi v2.0 schema.

I have a message which is a metadata message and defines the structure of another message, e.g. it uses the following parts in "schema" to define the allowed types:
```
    dpDataTypeV1:
      type: string
      oneOf:
        - const: 'Bool'
          x-dpDataType:
            $ref: "#/components/schemas/dpDataType_Bool"
        - const: 'Byte'
          x-dpDataType:
            $ref: "#/components/schemas/dpDataType_Byte"
 ...

    dpDataType_Bool:
      oneOf:
        - type: boolean
        - type: integer
          minimum: 0
          maximum: 1
        - type: string
          oneOf:
            - const: 'true'
            - const: 'false'
            - const: '0'
            - const: '1'

    dpDataType_Byte:
      oneOf:
        - type: integer
          minimum: 0
          maximum: 255
        - type: string
          regex: '^[1-9][0-9]{0,2}$'
```

The schema element of the value is defined like this:
```    dpValueVariantType:
      anyOf:
        - type: integer
        - type: number
        - type: string
        - type: boolean
        - type: object
        - type: array
```

Unfortunately the schema cannot be more specific, because the real type is dynamic, that's why I need a custom validator.

The other message with the values should then be validated, e.g. if the values really matches the definition of the metadata (e.g. the type and range).

I managed to find the correct schema element using this code:
```
    let dt = dpMeta.dataType;
    let schemaDt = validator.schema.components.schemas.dpDataTypeV1.oneOf.find(element => element.const == dt);
```

Unfortunately I didn't find a way how to call validate, e.g. with the value `true` and the schema element `dpDataType_Bool`.

Can you help me?

**Comment by nospam2000** [comment]
I think I found a solution by calling **validator._ajv.compile()** myself:
```
    let dt = dpMeta.dataType;
    let schemaDt = validator.schema.components.schemas.dpDataTypeV1.oneOf.find(element => element.const == dt);
    const vali = validator._ajv.compile(schemaDt["x-dpDataType"]);
    const result = vali(val.val);
    if (!result) {
      console.log(`Error: value "${val.val}" doesn't match type ${dt}`);
    }
```

**Comment by WaleedAshraf** [comment]
If I understood your problem correctly, the `dpDataType_Bool` is a message, then you should have it defined in your schema as a message.
It should have a topic (channel) and operation.

Something like this:


```yml
channels:
  data-types:
    description: data-types messages
    publish:
      message:
        name: dpDataType_Bool
        payload:
          oneOf:
            - type: boolean
            - type: integer
              minimum: 0
              maximum: 1
            - type: string
              oneOf:
                - const: 'true'
                - const: 'false'
                - const: '0'
                - const: '1'
```

```js
va.validate('dpDataType_Bool', message, 'data-types', 'publish')
```

**Comment by nospam2000** [comment]
the part
```
      anyOf:
        - type: integer
        - type: number
        - type: string
        -...
```
is a variant value and only one little part of the **value message**.

Another **metadata message** contains the definition which of the variant values of the **value message** has which concrete type. e.g. the anyof value 'Bool' in the metadata message  uses x-dpDataType to reference dpDataType_Bool which means dpDataType_Bool needs to be used to validate the variant of the value message.

The point is just that I need to be able to verify one single schema part against a value and not a whole message, because the rest of the message is already validated. For a whole validation of the value message additional external information from the metadata message is needed which contains the datatype definition.

**This seems to work with the lines I posted above**.

When I'm back at work next year I can post a more exhaustive example.

Thanks a lot for your validator, it is a big benefit for me!
