### ISSUE TITLE
How to use validate() with channel with parameter?

### ISSUE THREAD

**Issue by joerg-walter-de** [WaleedAshraf/asyncapi-validator#41]
I have a channel `/a/{id}/c`.

How do I use your validator with such a channel?

**Comment by WaleedAshraf** [comment]
It all depends on how your channel name is defined in the schema. For example, if it's like this.

```yaml
asyncapi: 2.0.0

info:
  title: User Events
  version: 1.0.0

channels:
  a/{id}/b:
    description: user related events
    publish:
      message:
        name: UserDeletedMessage
        x-custom-key: UserDeleted
        payload:
          ...
```

Then you can validate it like this,

```js
const AsyncApiValidator = require('asyncapi-validator')
let va = await AsyncApiValidator.fromSource('./api.yaml', {msgIdentifier: 'x-custom-key'})

// validate 'UserDeleted' on channel 'a/{id}/b' with operation 'publish'
va.validate('UserDeleted', {
  userId: '123456789',
  userEmail: 'alex@mail.com',
}, 'a/{id}/b', 'publish')
```

I haven't tried it, but I think it should work.
