### ISSUE TITLE
Bug: Validation fails with exclusiveMinimum / exclusiveMaximum in schema

### ISSUE THREAD

**Issue by joerg-walter-de** [WaleedAshraf/asyncapi-validator#45]
Version 3.1.1

fails with exclusiveMaximum active:

```
        myProperty:
          type: number
          minimum: 0.0
          maximum: 360.0
    # TODO     exclusiveMaximum: true
          example: 10.5
```

**Comment by WaleedAshraf** [comment]
Hi @joerg-walter-de,
Sorry for delayed response. You should use `exclusiveMaximum` as number, as defined in [JSON Schema Draft-06](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-01#section-6.3).

```yml
myProperty:
    type: number
    minimum: 0.0
    exclusiveMaximum: 360.0
    example: 10.5
```
