### ISSUE TITLE
Invalid message gets marked valid?

### ISSUE THREAD

**Issue by PanMan** [WaleedAshraf/asyncapi-validator#54]
Hi. Either I'm missing something, or the package doesn't actually.. Validate the message? 
Relevant code:
```
let validator: AsyncApiValidator.Validator;
const loadValidator = async () => {
  // Load the AsyncAPI validator. In a function as it's async
  validator = await AsyncApiValidator.fromSource(
    // Testing yaml:
    path.join(__dirname, "../spec/schemas/testschema.yaml")
  );
};
loadValidator();

const isValidMessage = validator.validateByMessageId(
    "UserRemoved",
    decodedMessage
  );
  console.log("Message is valid:", isValidMessage);
```

the testschema.yaml is the yaml from the [validatebymessageid example in the readme:]( https://github.com/WaleedAshraf/asyncapi-validator#example-usage-with-validatebymessageid-method)

However, when I run the above with a decodedMessage of: `{ timeout: 12 }` I get output: `Message is valid: true`

While none of the properties of the messages overlap?! It should obviously not be valid? Am I missing something here?

**Comment by WaleedAshraf** [comment]
There can be two reasons,
1. You are not awaiting `loadValidator();`
You can do it like this, by wrapping everything in async block

```js
(async function() {
  const loadValidator = ......
  await loadValidator();
  ....
})();
```

2: The other reason is that there's no check-in schema for additional properties. You can add it like this,
```yaml
...
messageId: UserRemoved
        payload:
          type: object
          additionalProperties: false
          properties:
            userEmail:
              type: string
...
```
